### ISSUE TITLE
How to remove specific generes

### ISSUE THREAD

**Issue by PixelJayden** [routayush1/animexninja#10]
Just had a question can i by any chance remove some generes from the website?

**Comment by ICEPrey** [comment]
Fork the api

**Comment by PixelJayden** [comment]
I have another question how can i add disques comment section ONLY in the watch pages?

**Comment by ICEPrey** [comment]
https://www.npmjs.com/package/disqus-react

**Comment by PixelJayden** [comment]
> https://www.npmjs.com/package/disqus-react

How do i set it up and how do i put it only in the /watch? (Sorry for all the questions)
