### ISSUE TITLE
API isnt pushing

### ISSUE THREAD

**Issue by PixelJayden** [routayush1/animexninja#13]
I put everything and named a folder in the website .env.local and i put BASE_URL="url" or should i put like BASE_URL="url/api/home" or something because it dosent want to upload animes etc..

**Comment by PixelJayden** [comment]
Unhandled Runtime Error
TypeError: Failed to fetch

i also get this

**Comment by PixelJayden** [comment]
@gauravdh9 Any idea how can i fix this

**Comment by gauravdh9** [comment]
actually we have source code for api but we can't disclose api url sorry for that

**Comment by gauravdh9** [comment]
in that base url your api end point will come

**Comment by gauravdh9** [comment]
if you want to check you can go through api repo clone it run it on some different port let say 5000

**Comment by gauravdh9** [comment]
then it will work but it will show you an error for different origin

**Comment by PixelJayden** [comment]
okay thank you ill try it out

**Comment by gauravdh9** [comment]
to fix that you have to install ngrok to make origin of your request same

**Comment by PixelJayden** [comment]
i use  ngrok on the api right?

**Comment by PixelJayden** [comment]
@gauravdh9 same error tho i changed the port to 8080

**Comment by routayush1** [comment]
pls run the api repo 
now in the website repo create a .env.local file and 
add

BASE_URL="LOCALHOST:5000/api/"

**Comment by PixelJayden** [comment]
okay thank you

**Comment by PixelJayden** [comment]
@routayush1 another question the website takes a few minutes to load (like going to the website) how can i make it run faster?

**Comment by ICEPrey** [comment]
> pls run the api repo
> now in the website repo create a .env.local file and
> add
> 
> BASE_URL="LOCALHOST:5000/api/"

I am having the same issue, my API works and runs locally. But when I build the file and upload it to the website hoster it doesn't work.
