### ISSUE TITLE
Design Suggestion

### ISSUE THREAD

**Issue by PixelJayden** [routayush1/animexninja#16]
@gauravdh9 heres some ideas i can give you for a anime watching vibe the design that is in the website i dont think its "meant" to be that design since its a anime website but heres a suggestion

https://9anime.to

**Comment by gauravdh9** [comment]
Appreciated for the suggestion.
But we kind of love originality and just inspiration and right now we are looking for some other projects and not just giving whole time to this website.We are only students we have a lot to do in College life this was just a fun project when we first made this we had no idea and made it in just 15 and half days so we kind of love this one and don't want any updation other than ours sorry for this..

**Comment by PixelJayden** [comment]
Yeah its fine
