### ISSUE TITLE
Watch.js

### ISSUE THREAD

**Issue by Abuws** [routayush1/animexninja#2]
The web streaming app doesn't load any video link, it's not a video player issue since I tried multiple. Also, no errors get logged.

**Comment by routayush1** [comment]
pls try again ,we have updated the repo

**Comment by Abuws** [comment]
Works thanks

**Comment by Abuws** [comment]
What if I wanted to use another player like https://www.npmjs.com/package/plyr-react

**Comment by routayush1** [comment]
You can, but code accordingly to the video source provided by api
