### ISSUE TITLE
Iphone

### ISSUE THREAD

**Issue by ICEPrey** [routayush1/animexninja#21]
Site doesn't work on iPhone browser safari.

**Comment by gauravdh9** [comment]
whats it showing send me screenshots

**Comment by ICEPrey** [comment]
Jus white screen no matter how many times i refresh

**Comment by ICEPrey** [comment]
![Uploading IMG-4879.PNG…]()

**Comment by ICEPrey** [comment]
![IMG-4879](https://user-images.githubusercontent.com/40725969/108586380-e2f88a00-7302-11eb-9042-43403bb4e361.PNG)

**Comment by gauravdh9** [comment]
do you have macbook or any apple branding  desktop or laptop? if you have then inspect and send image of console

**Comment by ICEPrey** [comment]
just opened safari on a macbook and It works. But on iphone it dosent....

**Comment by ICEPrey** [comment]
do you have discord? I can send you the video there

**Comment by gauravdh9** [comment]
check for updates on mobile then try

**Comment by ICEPrey** [comment]
![image](https://user-images.githubusercontent.com/40725969/108586814-a4180380-7305-11eb-823e-8e83b918e234.png)

**Comment by gauravdh9** [comment]
this can't be done becaue previous version of site was pure react based but now we are using next.js due to which next link dont work in iphones

**Comment by ICEPrey** [comment]
there is no way around it?

**Comment by ICEPrey** [comment]
reverting back to this issue, it was caused when you removed tailwind. I downloaded the old commit and tested it and it worked. https://github.com/routayush1/animexninja/commit/e80473b0801bb0b27c45764005fb89fd2a259cbd This is the commit I downloaded....
