### ISSUE TITLE
How can i upload anime sir? 

### ISSUE THREAD

**Issue by DevLucid-glitch** [routayush1/animexninja#24]
Thank you very much for this wonderful creation

**Comment by routayush1** [comment]
you cannot upload anime , actually its whole backend is just gogoanime

**Comment by DevLucid-glitch** [comment]
so.. how can i scrape anime from gogoanime?

**Comment by DevLucid-glitch** [comment]
> so.. how can i scrape anime from gogoanime?

can i have your email so we can talk about it

**Comment by routayush1** [comment]
you can visit and see our entire backend source

https://github.com/routayush1/animexninja-api

**Comment by DevLucid-glitch** [comment]
sir, I'm now running the api. now what do i do. sorry for inconvenience because I'm leaning and I'm new to this.

**Comment by DevLucid-glitch** [comment]
i fixed it now. you can close this thread sir. thank you for this wonderful creation.
