### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Vikram1234567** [routayush1/animexninja#30]
I dont understand how this work Please help.

**Comment by gauravdh9** [comment]
exactly which part you are not getting?

**Comment by Vikram1234567** [comment]
How to run it. Followed your instructions. Ran the Api, and ran the main. Then connected the api to the main. But I still get errors

**Comment by gauravdh9** [comment]
show errors

**Comment by fasih4444** [comment]
> show errors

![Uploading image.png…]()

**Comment by PaimonWheeWhee** [comment]
how did you self host it do tell

**Comment by fasih4444** [comment]
> how did you self host it do tell

Hahaha Got the error So No Need to Try

**Comment by fasih4444** [comment]
> how did you self host it do tell

When I open It keeps on loading & loading.

**Comment by PaimonWheeWhee** [comment]
oh
