### ISSUE TITLE
Adding A Random anime Feature

### ISSUE THREAD

**Issue by BlakenFist** [routayush1/animexninja#34]
Hey I was just Wondering If you can add a Feature So that the user can click a Button and a Random Anime will start Playing ?

This Guy is using your Build I guess, and added it - https://animumu.ga/popular/1

Also When I deployed The Site on My Hosting (https://thetvbuff.com/) Whenever we reload from a particular episode/ anime it redirects to the Homepage any Solutions for that?

**Comment by geetesh07** [comment]
> Hey I was just Wondering If you can add a Feature So that the user can click a Button and a Random Anime will start Playing ?
> 
> This Guy is using your Build I guess, and added it - https://animumu.ga/popular/1
> 
> Also When I deployed The Site on My Hosting (https://thetvbuff.com/) Whenever we reload from a particular episode/ anime it redirects to the Homepage any Solutions for that?

BLAKEN FIST YOUR SITE IS VERY NICE CAN YOU HELP ME TO SCRAPE LINK FOR MY SITE?

**Comment by Rajkumar-27** [comment]
Hey

**Comment by geetesh07** [comment]
> Hey

Please reply my mail

**Comment by PaimonWheeWhee** [comment]
How did you guys host it yourselves please tell me

**Comment by PaimonWheeWhee** [comment]
It would be nice if you also gave the source code

**Comment by geetesh07** [comment]
> It would be nice if you also gave the source code

Even i want to know how to host it on my site but idk how to do it

**Comment by PaimonWheeWhee** [comment]
Me too

**Comment by PaimonWheeWhee** [comment]
The repository owner said to get some sort of ngrok API link so I'm waiting for them to approve my API link request
