### ISSUE TITLE
how do you host this

### ISSUE THREAD

**Issue by PaimonWheeWhee** [routayush1/animexninja#41]

**Comment by Tetous** [comment]
follow the direction

**Comment by PaimonWheeWhee** [comment]
They're kinda vague

**Comment by Tetous** [comment]
mhm but it works

**Comment by PaimonWheeWhee** [comment]
would you mind giving me a step by step?

**Comment by fasih4444** [comment]
Same bro I wanna host this Can you please guide us. It would be Great Help. @routayush1
