### ISSUE TITLE
Project is Great but I wanna have this working. Please Help me.

### ISSUE THREAD

**Issue by fasih4444** [routayush1/animexninja#46]
Can you please giude me on How to host this Legendary Work on Hosting (CPANEL) Or Heroku or something like that.  It would be Great Help. @routayush1

**Comment by fasih4444** [comment]
If you can Please contact me here Telegram: t.me/@fasih4444

**Comment by Savvytar** [comment]
also i wanna know that, please letme know if you get this !

**Comment by geetesh07** [comment]
Hey i am in for it too.. the owner just doesnt reply

**Comment by fasih4444** [comment]
> Hey i am in for it too.. the owner just doesnt reply

Yeah I don't know. Why he's Avoiding? You can make a Guide. It's as simple as that.

**Comment by geetesh07** [comment]
> > Hey i am in for it too.. the owner just doesnt reply
> 
> Yeah I don't know. Why he's Avoiding? @gauravdh9 You can make a Guide. It's as simple as that.

Same dude.. i dont even know how to run it on local host

**Comment by gauravdh9** [comment]
Project is getting some issues until those are solved i can only reply this much.Please Cooperate

**Comment by geetesh07** [comment]
> Project is getting some issues until those are solved i can only reply this much.Please Cooperate

Its okay mate.. Not a problem but please make a video for newbies.. I cant even tell the amount of time i have spent on this .. @gauravdh9

**Comment by fasih4444** [comment]
Thanks @gauravdh9. I understand the shortage of time you've. But you can Give us a Time Frame you need to Fix.🙂

 Please Make a Guide on these:😃

How to host this on Heroku or Some other PF Like that.
How to host this on CPanel with React Js & Next Js supported

I'm not ordering bro. I'm just saying that'll benefit for us. As of Now no Perfect Explanation of Project. Thanks for All this. Keep it Up Guys. @routayush1 @sohamsingh29

**Comment by geetesh07** [comment]
> Thanks @gauravdh9. I understand the shortage of time you've. But you can Give us a Time Frame you need to Fix.🙂
> 
> Please Make a Guide on these:😃
> 
> How to host this on Heroku or Some other PF Like that.
> Or
> How to host this on CPanel with React Js & Next Js supported
> Or
> How to host this on a VPS
> 
> I'm not ordering bro. I'm just saying that'll benefit for us. As of Now, There's no Perfect Guide for Deploying this Project.
> Thanks for All of these. Keep it Up Guys. @routayush1 @sohamsingh29

@fasih4444 Can you help me in running it on local host?
