### ISSUE TITLE
Video Problem

### ISSUE THREAD

**Issue by animeawake** [routayush1/animexninja#54]
Video Playing Problem
videos not working

**Comment by Tetous** [comment]
Yeah, gogoanime got updated and now uses cloud fare

**Comment by PaimonWheeWhee** [comment]
Are there any other sites we can scrap data from?

**Comment by animeawake** [comment]
videos working on animex.ninja
but not for me

**Comment by geetesh07** [comment]
The export option is also not working!

**Comment by animeawake** [comment]
Well everything is working now

**Comment by PaimonWheeWhee** [comment]
This is a temporary solution. Gogoanime, which is where this site gets its anime from, has stopped using captcha on its downloads. That means that anyone who's scraping from Gogoanime can now download videos as they were able to before Gogoanime enabled captcha.
