### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by ICEPrey** [routayush1/animexninja#7]
Do you think it would be possible if you add MERN stack? For sign up and login auth?

**Comment by routayush1** [comment]
yes ,would love to add this too but my exams are near so would take some time

**Comment by Abuws** [comment]
Ah ok take care of that first then you can come back to this (Good luck).

**Comment by ICEPrey** [comment]
Another feature is, "On-card hover display summary and genres"

**Comment by ICEPrey** [comment]
Card can display latest episode and when the episode came out.
