### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by ICEPrey** [routayush1/animexninja#8]
Hey would be cool after you finish your exams to rework the API to switch from gogoanime to aniwatch.me? It features way more high-quality episodes and is just really more organized

**Comment by routayush1** [comment]
will try!!

**Comment by ICEPrey** [comment]
Thank you

**Comment by ICEPrey** [comment]
> will try!!

I am going to add more features in this threat/issue instead of just making new ones. I was thinking When you open the site back and it gives you the notification and you press it, it should also take you to your last time. So maybe save current.time in local storage?

**Comment by gauravdh9** [comment]
Resume functionality is added give a try

**Comment by ICEPrey** [comment]
> Resume functionality is added give a try

Works like a charm thank you
